#!/bin/bash

if [[ $OSTYPE = darwin* ]]; then
  sed="sed -E"
else
  sed="sed -r"
fi

$sed "/$1/ s/${2:-($1)}/$(echo @${2:-($1)}@ | sed 's/(.*)/'$(echo -e '\033[0;32m')'\\1'$(echo -e '\033[0m')'/' | $sed 's/(^@|@$)//g')/g"
